### PR TITLE
ISSUE-18 Error when adding URL

### PR DESCRIPTION
**Pull request by simba87**
Now soup operates with full html - it contains required page element for sure. Changed Parser to lxml - it is faster than standard parser.

After this fix applied, need to execute "pip3 install -r requirements.txt" again to get lxml parser.

### CODE REVIEW

**Comment by homelabtest** [comment]
Seems it is possible to start the program again, but the pornstar category still doesn't work (collected 0 videos for https://de.pornhub.com/pornstar/stacy-cruz).

I am new to Linux, so I tell you, what i did:
1) I created a new container and followed the standard installation.
2) I replaced the files requirements.txt and functions.py with your new files.
3) Then I executed 
apt-get install libxml2-dev libxslt-dev python-dev
pip3 install -r requirements.txt
4) After that:
python3 phdler.py add https://de.pornhub.com/pornstar/stacy-cruz
python3 phdler.py start
5) Output:
root@d5166c7e30a6:/PornHub-downloader-python-master# python3 phdler.py start
Running startup checks...
Database exists.
downloading new items
-----------------------------
pornstar
stacy-cruz
https://www.pornhub.com/pornstar/stacy-cruz
-----------------------------
[PornHubPagedVideoList] pornstar/stacy-cruz/videos: Downloading page 1
[download] Downloading playlist: pornstar/stacy-cruz/videos
[PornHubPagedVideoList] playlist pornstar/stacy-cruz/videos: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: pornstar/stacy-cruz/videos
downloading all items
-----------------------------
pornstar
stacy-cruz
https://www.pornhub.com/pornstar/stacy-cruz
-----------------------------
[PornHubPagedVideoList] pornstar/stacy-cruz/videos: Downloading page 1
[download] Downloading playlist: pornstar/stacy-cruz/videos
[PornHubPagedVideoList] playlist pornstar/stacy-cruz/videos: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: pornstar/stacy-cruz/videos
root@d5166c7e30a6:/PornHub-downloader-python-master#

**Comment by simba87** [comment]
Please see my response here: https://github.com/mariosemes/PornHub-downloader-python/issues/18

**Review by sirEgghead — APPROVED** [review]
Works on latest debian.  Would like to see this pr merged.  It's been open for 5 months.

**Comment by draconis10** [comment]
Tried the changes bdsmgeek made and still not working on windows, am I doing something wrong?

Running Windows 10 with Pyhton 3.8.6

**Comment by draconis10** [comment]
The problem with https://www.pornhub.com/pornstar/stacy-cruz is the pornhub profile doesn't have a /videos page which is causing the script to not find any videos.

[PornHubPagedVideoList] pornstar/stacy-cruz/videos: Downloading page 1
[download] Downloading playlist: pornstar/stacy-cruz/videos
[PornHubPagedVideoList] playlist pornstar/stacy-cruz/videos: Collected 0 video ids (downloading 0 of them)
[download] Finished downloading playlist: pornstar/stacy-cruz/videos
downloading all items

Looking at the script it shows **[download] Finished downloading playlist: pornstar/stacy-cruz/videos**, is there any way to remove the /videos part?

**Review by mariosemes — APPROVED** [review]
Hope its gonna work, but the development is deprecated.

**Pull request merged**
